import type { InfoEntry, NutritionMetric, NutritionType, RecipeSnapshot, SourceMetric, SourceType } from './models';
import { NUTRITION, NUTRITION_META, SOURCES, SOURCE_META } from './models';
export function totalMinutesOf(entries: InfoEntry[]): number { return entries.reduce((sum, item) => sum + item.minutes, 0); }
export function metricsFor(entries: InfoEntry[]): NutritionMetric[] { const total = totalMinutesOf(entries); return NUTRITION.map((nutrition) => { const minutes = entries.filter((item) => item.nutrition === nutrition).reduce((sum, item) => sum + item.minutes, 0); const meta = NUTRITION_META[nutrition]; return { nutrition, minutes, share: total ? minutes / total : 0, target: meta.target, color: meta.color, icon: meta.icon }; }); }
export const SOURCE_OVER_RATIO = 0.35;
export function sourceMetricsFor(entries: InfoEntry[]): SourceMetric[] { const total = totalMinutesOf(entries); return SOURCES.map((source) => { const minutes = entries.filter((item) => item.source === source).reduce((sum, item) => sum + item.minutes, 0); const meta = SOURCE_META[source]; return { source, minutes, share: total ? minutes / total : 0, color: meta.color, icon: meta.icon }; }); }
export function topNutritionsFor(entries: InfoEntry[], source: SourceType, limit = 2): Array<{ nutrition: NutritionType; minutes: number }> { return NUTRITION.map((nutrition) => ({ nutrition, minutes: entries.filter((item) => item.source === source && item.nutrition === nutrition).reduce((sum, item) => sum + item.minutes, 0) })).filter((item) => item.minutes > 0).sort((a, b) => b.minutes - a.minutes).slice(0, limit); }
export function sourceDiagnoses(metrics: SourceMetric[]): string[] { const result: string[] = []; metrics.forEach((item) => { if (item.share > SOURCE_OVER_RATIO) result.push(`「${item.source}」占到全部摄入的 ${Math.round(item.share * 100)}%，来源结构失衡。${SOURCE_META[item.source].overHint}`); }); return result.length ? result : ['来源结构分布均衡，没有过度依赖单一内容形式。']; }
export function diagnoses(metrics: NutritionMetric[]) { const result: string[] = []; metrics.forEach((item) => { if (item.share > item.target + 0.12) result.push(`「${item.nutrition}」摄入偏高，已经占到 ${Math.round(item.share * 100)}%，建议下一餐换一种营养。`); if (item.share < item.target - 0.1) result.push(`「${item.nutrition}」长期偏少，建议本周补充 ${Math.max(20, Math.round(item.target * 180 - item.minutes))} 分钟。`); }); return result.length ? result : ['你的信息餐盘接近均衡，继续保持“先深后浅”的摄入顺序。']; }
export function mealScore(metrics: NutritionMetric[]): number { return Math.max(0, Math.round(100 - metrics.reduce((sum, item) => sum + Math.abs(item.share - item.target) * 100, 0) * 0.9)); }
export function createEntry(title: string, source: SourceType, nutrition: NutritionType, minutes: number, note: string, date = new Date().toISOString().slice(0, 10)): InfoEntry { return { id: `info-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, title: title.trim() || '未命名内容', source, nutrition, minutes: Math.max(1, Number(minutes) || 1), date, note: note.trim() }; }
export function sampleSnapshot(): RecipeSnapshot { const seed: Array<[string, SourceType, NutritionType, number]> = [['设计系统拆解', '文章', '深度知识', 45], ['本周产品新闻', '播客', '行业动态', 28], ['TypeScript 实战', '视频', '技能提升', 38], ['朋友动态', '社交媒体', '社交信息', 24], ['短篇小说', '书籍', '娱乐消遣', 32], ['用户研究方法', '文章', '深度知识', 36], ['灵感合集', '视频', '娱乐消遣', 18]]; return { dailyGoal: 150, entries: seed.map(([title, source, nutrition, minutes], index) => createEntry(title, source, nutrition, minutes, index % 2 ? '收藏后完成了记录。' : '带着问题去消费。', new Date(Date.now() - index * 86400000).toISOString().slice(0, 10))) }; }
